### ISSUE TITLE
The remaining tries should be stored and accessed. A MUST.

### ISSUE THREAD

**Issue by IamGoatCoder** [Idrisvohra9/react-enigma-pattern-lock#1]
The package is fire, and I had no problem integrating it in my project.

But there is one important thing that has been missed, and that is the component should remember the remaining tries on page refresh or that can be considered as a loophole for unlimited tries.

**Comment by Idrisvohra9** [comment]
Yeah, a good point here, I will be adding the feature that saves the remaining tries on page refresh.

Thank You.
